import Head from 'next/head';

// icons
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube } from 'react-icons/ai';

// images
import Image from 'next/image';
import deved from '../public/dev-ed-wave.png';
import design from '../public/design.png';
import code from '../public/code.png';
import consulting from '../public/consulting.png';
import web1 from '../public/web1.png';
import web2 from '../public/web2.png';
import web3 from '../public/web3.png';
import web4 from '../public/web4.png';
import web5 from '../public/web5.png';
import web6 from '../public/web6.png';

// dark mode
import { useState } from 'react';

// custom
import { AiFillHeart } from 'react-icons/ai';


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Dmitri Marco Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/avatar.png" />
      </Head>

      <main className=' bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900 transition-colors ease-in-out duration-300'>
        {/* header section */}
        <section className='min-h-screen'>
          {/* nav section */}
          <nav className=' py-10 mb-1 flex justify-between '>
            <h1 className='text-xl font-burtons dark:text-white'>developedbyed</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl dark:text-white' />
              </li>
              <li><a href="#" className=' bg-gradient-to-r from-cyan-500 to-green-300 text-white px-4 py-2 border-none rounded-md ml-8'>Resume</a></li>
            </ul>
          </nav>
          {/* hero section */}
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-semibold md:text-6xl'>Dimitri Marco</h2>
            <h3 className='text-2xl py-2 md:text-3xl dark:text-white'>Developer and designer.</h3>
            <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-gray-400'>Freelancer providing services for programming and design content need. Join me down below and let's get cracking!</p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillYoutube />
          </div>
          <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96'>
            <Image src={deved} alt='' layout='fill' objectFit='cover' />
          </div>
        </section>
        {/* Services offering section */}
        <section>
          <div>
            <h3 className='text-3xl py-1 lg:text-4xl dark:text-white'>Services I offer</h3>
            <p className='text-md py-2 leading-8 text-gray-800 lg:text-lg max-w-xl dark:text-gray-400'>
              Since the beginning of my journey as a freelance designer and developer, I've done remote work for <span className='text-teal-500'>agencies</span> consulted for <span className=' text-teal-500'>startups</span> and collaborated with talanted people to create digital products for both business and consumer use.
            </p>
            <p className='text-md py-2 leading-8 text-gray-800 lg:text-lg dark:text-gray-400'>
              I offer from a wide large of services, including brand design, programming and teaching.
            </p>
          </div>
          <div className='gap-10 lg:flex lg:justify-around'>
            <div className='text-center shadow-xl p-10 rounded-xl my-10'>
              <Image src={design} alt='' width={100} height={100} className='mx-auto' />
              <h3 className='text-lg font-semibold pt-8 pb-2 dark:text-white'>Beautiful Designs</h3>
              <p className='py-2 dark:text-white'>Creating elegant designs suited for your needs following core design theory.</p>
              <h4 className='py-4 text-teal-600'>Design tools I use</h4>
              <p className='text-gray-800 py-1 dark:text-gray-400'>Photoshop</p>
              <p className='text-gray-800 py-1 dark:text-gray-400'>Illustrator</p>
              <p className='text-gray-800 py-1 dark:text-gray-400'>Figma</p>
            </div>
            <div className='text-center shadow-xl p-10 rounded-xl my-10'>
              <Image src={consulting} alt='' width={100} height={100} className='mx-auto' />
              <h3 className='text-lg font-semibold pt-8 pb-2 dark:text-white'>Beautiful Designs</h3>
              <p className='py-2 dark:text-white'>Creating elegant designs suited for your needs following core design theory.</p>
              <h4 className='py-4 text-teal-600'>Design tools I use</h4>
              <p className='text-gray-800 py-1 dark:text-gray-400'>Photoshop</p>
              <p className='text-gray-800 py-1 dark:text-gray-400'>Illustrator</p>
              <p className='text-gray-800 py-1 dark:text-gray-400'>Figma</p>
            </div>
            <div className='text-center shadow-xl p-10 rounded-xl my-10'>
              <Image src={code} alt='' width={100} height={100} className='mx-auto' />
              <h3 className='text-lg font-semibold pt-8 pb-2 dark:text-white'>Beautiful Designs</h3>
              <p className='py-2 dark:text-white'>Creating elegant designs suited for your needs following core design theory.</p>
              <h4 className='py-4 text-teal-600'>Design tools I use</h4>
              <p className='text-gray-800 py-1 dark:text-gray-400'>Photoshop</p>
              <p className='text-gray-800 py-1 dark:text-gray-400'>Illustrator</p>
              <p className='text-gray-800 py-1 dark:text-gray-400'>Figma</p>
            </div>
          </div>
        </section>
        {/* Portfolio section */}
        <section>
          <div className=''>
            <h3 className='text-3xl py-1 dark:text-white'>Portfolio</h3>
            <p className='text-md py-2 leading-8 text-gray-800 lg:max-w-xl dark:text-gray-400'>
              Since the beginning of my journey as a freelance designer and developer, I've done remote work for <span className='text-teal-500'>agencies</span> consulted for <span className=' text-teal-500'>startups</span> and collaborated with talanted people to create digital products for both business and consumer use.
            </p>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-400'>
              I offer from a wide large of services, including brand design, programming and teaching.
            </p>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className=' basis-1/3 flex-1'>
              <Image src={web1} alt='' className='rounded-lg object-cover shadow-xl' width={'100%'} height={'100%'} layout="responsive" />
            </div>
            <div className=' basis-1/3 flex-1'>
              <Image src={web2} alt='' className='rounded-lg object-cover shadow-xl' width={'100%'} height={'100%'} layout="responsive" />
            </div>
            <div className=' basis-1/3 flex-1'>
              <Image src={web3} alt='' className='rounded-lg object-cover shadow-xl' width={'100%'} height={'100%'} layout="responsive" />
            </div>
            <div className=' basis-1/3 flex-1'>
              <Image src={web4} alt='' className='rounded-lg object-cover shadow-xl' width={'100%'} height={'100%'} layout="responsive" />
            </div>
            <div className=' basis-1/3 flex-1'>
              <Image src={web5} alt='' className='rounded-lg object-cover shadow-xl' width={'100%'} height={'100%'} layout="responsive" />
            </div>
            <div className=' basis-1/3 flex-1'>
              <Image src={web6} alt='' className='rounded-lg object-cover shadow-xl' width={'100%'} height={'100%'} layout="responsive" />
            </div>
          </div>
        </section>
        {/* custom section */}
        <section>
          <div className='flex py-6'>
            <h2 className='mx-auto text-xl flex dark:text-white'>With <AiFillHeart className='text-red-500 text-3xl mx-1' /> by Kotiasv</h2>
          </div>
        </section>
      </main>
    </div>
  );
}
